modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/LatvianModder/Common-Resources/issues"

[[mods]]
modId = "commonresources"
version = "${file.jarVersion}"
displayName = "Common Resources"
authors = "LatvianModder"
description = '''
Adds commonly used metals and gems
'''
license = "GNU LGPLv3"

[[dependencies.commonresources]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.commonresources]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"